export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAILURE = "GET_COMPANIES_FAILURE";

export const SEARCH_COMPANIES_BY_SEARCH_TERM = "SEARCH_COMPANIES_BY_SEARCH_TERM";

export const POPULATE_USER = 'POPULATE_USER';
